runtime: nodejs16
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
- url: /
  static_files: dist/angular-ecom/index.html
  upload: dist/angular-ecom/index.html
- url: /
  static_dir: dist/angular-ecom
